### ISSUE TITLE
[Question] Which Hardware do i need?

### ISSUE THREAD

**Issue by GregOnNet** [Doerki/Room-Presence-Service#7]
Hey guys,

awesome work!
I really like your project.

Can you assist in telling me which hardware I need to bootstrap my own _Room-Presence-Service_ ? :+1: 

Kind regards
Greg

**Comment by d-koppenhagen** [comment]
you just need a Raspberry PI, some LEDs, so few cables to connect them, and maybe a resistor or Opto-isolator.

**Comment by d-koppenhagen** [comment]
for release 2.0 you need RGB LEDs

**Comment by GregOnNet** [comment]
Thx for the update @Doerki !

**Comment by fmalcher** [comment]
We should provide schematics and part lists in the repo... ;-)

**Comment by fmalcher** [comment]
@Doerki Better use transistors XOR opto-isolators and a separate power supply for the LEDs. The raspi doesn't provide enough power and voltage for the LEDs
